title: Welcom to my blog
author: AA
email: myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Title is the new title and blog is the new blog.
  Roses are roses are roses.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage


theme: jekyll-theme-merlot
