title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description for my post. Just a brief description here
# social links
twitter_username: @-----------nonamehere
github_username:   @-----------nonamehere

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
